openapi: 3.0.0
info:
  title: cpuinfo
  description: A simple service to get cpuinfo as an example of using OpenAPI 3.0
  license:
    name: Apache 2.0
  version: 0.0.1

servers:
  - url: http://129.114.32.42:22/cloudmesh

paths:
  /cpu:
    get:
      summary: Returns cpu information of the hosting server
      operationId: cpu.get_processor_name
      responses:
        '200':
          description: cpu info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/cpu"
                
  /cpu_cache/{cache_level}:
    get:
      summary: Returns cache size information of the hosting server
      operationId: cpu.get_cache_sizes
      responses:
        '200':
          description: cache size info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/level"
      parameters:
        - name: cache_level
          in: path
          required: true
          description: Cache level
          schema:
            type: string

  /cpu_cache:
    get:
      summary: Returns cache size information of the hosting server
      operationId: cpu.get_both_cache_sizes
      responses:
        '200':
          description: cache size info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/level"


components:
  schemas:
    cpu:
      type: "object"
      required:
        - "model"
      properties:
        model:
          type: "string"
    level:
      type: "object"
      properties:
        l2_cache_size:
          type: "string"
        l3_cache_size:
          type: "string"