version: '3'
services:
        mongo:
                image: mongo:latest
                environment:
                        - MONGO_INITDB_ROOT_USERNAME=root
                        - MONGO_INITDB_ROOT_PASSWORD=pass
                ports:
                        - "27017:27017"
                container_name: mongoContainerAuth
                command: mongod
        mongoClientAuth:
                image: mongo:latest
                container_name: mongoClientAuth
                depends_on:
                        - mongo
