version: '3'
services:
        cloudmesh:
                image: cloudmesh/cloudmesh-cms:latest
                container_name: airflow_cloudmesh
                volumes:
                        - .:/cloudmesh
                        - ~/.cloudmesh:/root/.cloudmesh
                        - ~/.ssh:/root/.ssh:ro
                        - //c/users/austin/cm/cloudmesh-cloud/docker/cms-ubuntu-19.04/dags:/usr/local/airflow/dags
                        - //c/users/austin/cm/cloudmesh-cloud/docker/cms-ubuntu-19.04/pytests:/cm/pytests
                        - //c/users/austin/cm/cloudmesh-cloud/docker/cms-ubuntu-19.04/cms_scripts:/cm/cms_scripts
                        - //c/users/austin/cm/cloudmesh-cloud/docker/cms-ubuntu-19.04/aws/credentials:/root/.aws/credentials
                        - //c/users/austin/cm/cloudmesh-cloud/docker/cms-ubuntu-19.04/pass.txt:/root/pass/pass.txt
                depends_on:
                        - postgres
                ports:
                        - "8080:8080"
                environment:
                        - AIRFLOW__CORE__LOAD_EXAMPLES=False
                entrypoint: /entrypoint.sh

        postgres:
                image: postgres:latest
                container_name: airflow_postgres
                ports:
                        - "5432:5432"
                environment:
                        - POSTGRES_USER=airflow
                        - POSTGRES_PASSWORD=airflow
                        - POSTGRES_DB=airflow
                volumes:
                        - postgres-volume:/var/lib/postgresql/data

volumes:
        postgres-volume:
                external: false
