version: '3'
services:
        cloudmesh:
                image: cloudmesh/cloudmesh-cms:latest
                container_name: airflow_cloudmesh
                volumes:
                        - .:/cloudmesh
                        - ~/.cloudmesh:/root/.cloudmesh
                        - ~/.ssh:/root/.ssh
                        - //c/users/austin/cm/cloudmesh-cloud/docker/cms-ubuntu-19.04/dags:/usr/local/airflow/dags
                depends_on:
                        - postgres
                ports:
                        - "8080:8080"
                environment:
                        - AIRFLOW__CORE__LOAD_EXAMPLES=False
                entrypoint: /entrypoint.sh

        postgres:
                image: postgres:latest
                container_name: airflow_postgres
                ports:
                        - "5432:5432"
                environment:
                        - POSTGRES_USER=airflow
                        - POSTGRES_PASSWORD=airflow
                        - POSTGRES_DB=airflow
                volumes:
                        - postgres-volume:/var/lib/postgresql/data

        pgadmin:
                image: dpage/pgadmin4:latest
                container_name: airflow_pgadmin
                depends_on:
                        - postgres
                ports:
                        - "80:80"
                environment:
                        - PGADMIN_DEFAULT_EMAIL=postgres
                        - PGADMIN_DEFAULT_PASSWORD=admin

volumes:
        postgres-volume:
                external: false
