version: '3'
services:
        postgres:
                image: postgres:latest
                container_name: airflow_postgres
                environment:
                        - POSTGRES_USER=airflow
                        - POSTGRES_PASSWORD=airflow
                        - POSTGRES_DB=airflow

        pgadmin:
                image: dpage/pgadmin4:latest
                container_name: airflow_pgadmin
                depends_on:
                        - postgres
                ports:
                        - "80:80"
                environment:
                        - PGADMIN_DEFAULT_EMAIL=postgres
                        - PGADMIN_DEFAULT_PASSWORD=admin

        webserver:
                image: airflow:latest
                container_name: airflow_webserver
                restart: always
                depends_on:
                        - postgres
                volumes:
                        - //c/users/azebrowski/testme/dags:/usr/local/airflow/dags
                ports:
                        - "8080:8080"
                entrypoint: /entrypoint.sh
