version: '3'
services:
        cloudmesh:
            build: .
            container_name: cloudmesh
            volumes:
                - .:/code
                - ~/.cloudmesh:/root/.cloudmesh
                - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
                - //c/users/austin/testme:/usr/local/airflow/dags
            depends_on:
                - mongo
                - postgres
            links:
                - mongo
            restart: always
            ports:
                    - "8080:8080"
            entrypoint: /entrypoint.sh

        postgres:
                image: postgres:latest
                container_name: airflow_postgres
                environment:
                        - POSTGRES_USER=airflow
                        - POSTGRES_PASSWORD=airflow
                        - POSTGRES_DB=airflow

        pgadmin:
                image: dpage/pgadmin4:latest
                container_name: airflow_pgadmin
                depends_on:
                        - postgres
                ports:
                        - "80:80"
                environment:
                        - PGADMIN_DEFAULT_EMAIL=postgres
                        - PGADMIN_DEFAULT_PASSWORD=admin
                
        mongo:
                image: mongo:latest
                container_name: mongodb
                restart: always
                environment:
                    MONGO_INITDB_ROOT_USERNAME: azebrows
                    MONGO_INITDB_ROOT_PASSWORD: *****
                    MONGO_INITDB_DATABASE: cloudmesh
                    ports: "27017-27019:27017-27019"
                    volumes: ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
