version: '3'
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: airflowtest
        depends_on:
            - postgres
        ports:
            - "8080:8080"
        command: airflow webserver -p 8080
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
